-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "deliveryBaseCost" DOUBLE PRECISION NOT NULL DEFAULT 10000,
ADD COLUMN     "expressShippingCost" DOUBLE PRECISION NOT NULL DEFAULT 2500,
ADD COLUMN     "freeShippingThreshold" DOUBLE PRECISION NOT NULL DEFAULT 120000;
