import type { Metadata } from "next";
import { inter } from "@/config/fonts";

import "./globals.css";
import { Providers, GoogleAnalytics, PageViewTracker } from "@/components";



export const metadata: Metadata = {
  title: {
    template: '%s - Tienda | Online',
    default: 'Home - Tienda | Online'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Google Analytics 4 */}
        <GoogleAnalytics 
          measurementId={process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID || ''} 
        />
        
        <Providers>
          {/* Page View Tracker */}
          <PageViewTracker />
          {children}
        </Providers>
      </body>
    </html>
  );
}
