import type { Metadata } from "next";
import { inter } from "@/config/fonts";

import "./globals.css";
import { Providers, WhatsAppFloat } from "@/components";



export const metadata: Metadata = {
  title: {
    template: '%s - Tienda | Online',
    default: 'Home - Tienda | Online'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
        {/* WhatsApp Float Button - aparece en todas las páginas */}
        <WhatsAppFloat
          phoneNumber={process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "1234567890"}
          message={process.env.NEXT_PUBLIC_WHATSAPP_MESSAGE}
          position="bottom-right"
        />
      </body>
    </html>
  );
}
